"""Shared categorisation configuration used by ingestion + API routes."""

BUILTIN_CATEGORIES = [
    "Bills",
    "Entertainment",
    "Food",
    "Savings",
    "Shopping",
    "Transport",
    "Transfer",
]

# Built-in keyword rules used for deterministic pre-categorisation.
CATEGORY_RULES = {
    "Bills": [
        "British Gas",
        "Thames Water",
        "Council Tax",
        "Hyperoptic",
        "O2",
        "Sky",
        "American Express",
        "Amex",
        "Rent",
    ],
    "Entertainment": [
        "Netflix",
        "Spotify",
        "Steam",
        "Cinema",
        "Apple",
        "Microsoft",
        "Golf",
    ],
    "Food": [
        "Tesco",
        "Sainsbury",
        "Ocado",
        "Waitrose",
        "Lidl",
        "Aldi",
        "Pizza Hut",
        "Domino",
        "McDonald's",
        "KFC",
        "Deliveroo",
        "Uber Eats",
        "Pret",
        "Nandos",
    ],
    "Savings": [
        "Chase Saver",
        "Round Up",
        "ISA",
        "Pension",
        "Savings",
    ],
    "Shopping": [
        "Amazon",
        "ASOS",
        "Ebay",
        "John Lewis",
        "TK Maxx",
        "Instalment Plan",
        "Payment Received",
    ],
    "Transport": [
        "TFL",
        "Trainline",
        "Uber",
        "Shell",
        "BP",
        "National Rail",
    ],
    "Transfer": [
        "Transfer",
        "Credit Card Payment",
        "Balance Payment",
        "Faster Payment",
    ],
}
